### ISSUE TITLE
Remove all overlay spinner

### ISSUE THREAD

**Issue by stevensdavid** [stevensdavid/fantasy#6]

**Comment by stevensdavid** [comment]
@ruwaid123 What are you suggesting instead?

**Comment by ruwaid123** [comment]
most likely activity indicator

**Comment by ruwaid123** [comment]
Use <View pointerEvents={this.state.loading ? "none" : "auto"}>
on top parent view to disable touch input and an activity indicator put somewhere appropriate which conditionally renders on this.state.loading

**Comment by ruwaid123** [comment]
Removed from LoginForm

**Comment by ruwaid123** [comment]
To remove from:
* EventView
* LeaguesHome
* EditProfile
* FriendView
* ProfileView
* RegisterForm
* TournamentView

**Comment by ruwaid123** [comment]
Ruwaid is on this

**Comment by ruwaid123** [comment]
DONE!
